### ISSUE TITLE
Video has autoplay attribute without muted attribute

### ISSUE THREAD

**Issue by InjuMichorius** [davidvanr21/portfolio#6]
Hey David.
A lot of browsers block autoplayed video's if the video is not muted. I think you can guess why ;).

Suggested change:
```html
<video controls autoplay muted loop>
        <source src="img/homepage/brandstov_showreel.mp4" type="video/mp4">
        Your browser does not support the video tag.
</video>

**Comment by davidvanr21** [comment]
Added the `muted` inside the HTML tag and it's running perfectly now. Thanks @InjuMichorius Inju! 🥳
